window.env = {
   api: {
      authUrl: 'https://api.heavenexchange.io/api/v2/account',
      tradeUrl: 'https://api.heavenexchange.io/api/v2/exchange',
      finexUrl: 'https://api.heavenexchange.io/api/v2/finex',
      applogicUrl: 'https://api.heavenexchange.io/api/v2/applogic',
      rangerUrl: 'wss://api.heavenexchange.io/api/v2/ranger',
      p2pUrl: 'https://api.heavenexchange.io/api/v2/p2p',
      newsUrl: 'https://news.digiassetindo.com/ghost/api/v3/content/posts',
   },
   minutesUntilAutoLogout: '35',
   withCredentials: true,
   finex: false,
   gaTrackerKey: '',
   rangerReconnectPeriod: '1',
   msAlertDisplayTime: '5000',
   incrementalOrderBook: true,
   isResizable: false,
   isDraggable: false,
   languages: ['en'],
   sessionCheckInterval: '15000',
   balancesFetchInterval: '5000',
   passwordEntropyStep: 14,
   showLanding: true,
   sentryEnabled: false,
   kycSteps: [
      'email',
      // 'phone',
      'profile',
      'document',
      // 'address',
   ],
};
